### ISSUE TITLE
Ctrl-C does not interrupt computation in standalone mode

### ISSUE THREAD

**Issue by dundalek** [trptcolin/reply#188]
Steps to reproduce:
- Clone the repo
- From the repo directory run `lein trampoline run --standalone`
- In the REPL run a loop, e.g. `(doseq [i (range 1e6)] (println i))`
- Numbers get printed to the output, hit Ctrl-C

Expected: Computation gets interrupted and the prompt is shown to accept new input.
Actual: Computation continues until it finishes naturally.

It is interesting to compare that the nrepl mode (`lein trampoline run`) works as expected and interrupts. I tried both master and latest release tag `0.4.1`.

I am running Ubuntu Linux, tried it in Gnome Terminal and urxvt, started from bash.

CLJ/Java versions:
```
REPL-y 0.4.1, nREPL 0.4.1
Clojure 1.6.0
Java HotSpot(TM) 64-Bit Server VM 1.8.0_181-b13
```

**Comment by trptcolin** [comment]
First, great issue report, makes total sense. I ran this locally and I did eventually see this:

```
#<ThreadDeath java.lang.ThreadDeath>
user=> ;;;;;;;;;;
; Sorry, have to call Thread.stop on this command.
;;;;;;;;;;
```

Is it possible that message gets printed for you eventually, just delayed longer than you'd like? There's a 2-second sleep that we could remove to make that cancellation more responsive. When I wrote this bit in 2012, I think I was worried about `Thread.stop` based on the [scary javadoc deprecation warnings](https://docs.oracle.com/javase/7/docs/api/java/lang/Thread.html#stop()), and the uncertainty around how people might want to use `reply`, but these days since [nREPL does `.stop`](https://github.com/nrepl/nREPL/blob/e77945a70f68989f69e955eef9e6cbe75cedacf4/src/clojure/nrepl/middleware/interruptible_eval.clj#L239) and that's the dominant use case for `reply`, I'd definitely be open to just [deleting this line](https://github.com/trptcolin/reply/blob/cefadce20024676428f3933af8da0ed88688359e/src/clj/reply/eval_modes/standalone/concurrency.clj#L29).

**Comment by dundalek** [comment]
Cool, thank you. You are right, `Thread.stop` gets eventually called (I haven't seen it before because the calculation finished before the delay kicked in). And commenting out that line makes it interrupt immediately.

I imagine `Thread.stop` could have potentially nasty consequences in a multi-threaded server app so that might be why they discourage it. In the repl it might be probably fine, but I am no expert on the matter :)

**Comment by trptcolin** [comment]
Sweet. Want to give me a PR to delete that line? I'm OK with it; otherwise I will get to it at some point.
