### ISSUE TITLE
Is there a way to get an nREPL message log?

### ISSUE THREAD

**Issue by PEZ** [trptcolin/reply#210]
Hi! Thanks for providing REPL-y!

I'm debugging an nREPL related issue with Calva and use REPL-y for comparison when I want to remove Calva from the picture. In trying to figure out what REPL-y and Calva might be doing differently it would help a lot with a log of the nREPL messages sent and recieved from REPL-y. Is it possible to enable such a thing? And, if so, how do I do it?

**Comment by trptcolin** [comment]
It’s been a long time since I worked on this but I know there’s a concept of nrepl middleware at the nrepl server side - wonder if that could be helpful here? I don’t think there’s anything built in afaik, but I imagine for debugging purposes you could try tweaking https://github.com/trptcolin/reply/blob/main/src/clj/reply/eval_modes/nrepl.clj to add some `println` or something?

**Comment by PEZ** [comment]
Thanks! I'll have a look.

**Comment by bbatsov** [comment]
Experience has taught me that it's much easier to have this logging on the client side, than on the server. :-) See also https://github.com/nrepl/nrepl/issues/85 and https://github.com/lambdaisland/nrepl-proxy

**Comment by PEZ** [comment]
OMG. This in the announcements channel over at Clojurians slack an hour ago:

<img width="1036" alt="image" src="https://user-images.githubusercontent.com/30010/190575554-5758ea28-b311-483b-9529-aa3b81d2a369.png">

**Comment by bbatsov** [comment]
@PEZ Coincidence or providence? ;-) (see https://github.com/lambdaisland/nrepl-proxy/issues/1)

**Comment by PEZ** [comment]
Haha, I see what you did there.
